# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diario',
            old_name='date_entrada',
            new_name='data_entrada',
        ),
    ]
